name: Automate Credential Report
on:
  # trigger manually
  workflow_dispatch:

jobs:
  generate-export-credential-report:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Verify aws
        run: aws --version

      - name: Configure AWS Credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials
      
      - name: Verify AWS Credential
        run: aws configure list

      - name: Verify s3 permission
        run: aws s3 ls
      
      - name: Generate Credential Report
        run: aws iam generate-credential-report
      
      - name: Wait for 5 second
        run: sleep 5
      
      - name: Retrieve report
        run: report_content=$(aws iam get-credential-report --query 'Content' --output text)
      
      - name: Verify report_content
        run: echo $report_content  

      - name: Decode report
        run: report_text=$(echo "$report_content" | base64 -d)
      
      - name: Save report to csv file
        run: echo "$report_text" > credential-report.csv
      
      - name: Copy the report to s3
        run: aws s3 cp ./credential-report.csv s3://keypair-1234